#!/system/bin/sh

KERNEL_MODULE_DIR=/lib/modules
ROM_MODULE_DIR=/system/lib/modules

function makeWritable {
    mount -o remount,rw /system
}

function makeReadonly {
    mount -o remount,ro /system
}

if [ ! -e $ROM_MODULE_DIR ]
then
    makeWritable
    mkdir $ROM_MODULE_DIR
    makeReadonly
fi

cd $ROM_MODULE_DIR
for file in *.ko
do
    if [ $file == "*.ko" ]
    then
        break;
    fi
    
    if [ -e $KERNEL_MODULE_DIR/$file ]
    then
        MD5SUM_ROM=`/system/xbin/md5sum $file | cut -d' ' -f1`
        MD5SUM_KERNEL=`/system/xbin/md5sum $KERNEL_MODULE_DIR/$file | cut -d' ' -f1`
        if [ $MD5SUM_ROM != $MD5SUM_KERNEL ]
        then
            #echo "Kernel module $file is different to kernel"
            makeWritable
            cp $KERNEL_MODULE_DIR/$file $file
            makeReadonly
        fi
    fi
done

# copy all not in /system/lib/modules
cd $KERNEL_MODULE_DIR
for file in *.ko
do
    if [ $file == "*.ko" ]
    then
        break;
    fi

    if [ ! -e $ROM_MODULE_DIR/$file ]
    then
        #echo "Kernel module $file is different to kernel"
        makeWritable
        cp $file $ROM_MODULE_DIR/$file
        makeReadonly
    fi
done
